slurm_install_pyxis: true
slurm_install_prefix: /usr/local
slurm_config_dir: /etc/slurm
slurmctl_config_dir: /sw/.slurm
slurm_pyxis_version: 0.11.1
slurm_pyxis_tarball_url: "https://github.com/NVIDIA/pyxis/archive/v{{ slurm_pyxis_version }}.tar.gz"

is_controller: no
is_compute: no

pyxis_ubuntu_deps:
- "bsdmainutils"

pyxis_el_deps:
- "util-linux"
